# Generated by Django 4.0.2 on 2022-04-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserListenedTo',
        ),
    ]
