# Generated by Django 4.0.2 on 2022-04-05 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_app', '0002_delete_userlistenedto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListenedTo',
            fields=[
                ('ultID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FK_release_date_LT', models.DateField(default='2022-01-01')),
                ('FK_ratingLT', models.DecimalField(decimal_places=1, default=7.5, max_digits=5)),
                ('FK_albumID_userLT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_app.album')),
                ('FK_artistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_app.artist')),
                ('FK_recordLabelID_LT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album_app.recordlabel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
