# Generated by Django 4.0.2 on 2022-04-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0003_userlistenedto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
