# Generated by Django 4.0.2 on 2022-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistenedto',
            name='relisten',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False),
        ),
    ]
