# Generated by Django 4.0.2 on 2022-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0006_remove_album_relisten'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlistenedto',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
