# Generated by Django 4.0.2 on 2022-04-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0007_userlistenedto_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistenedto',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
