# Generated by Django 4.0.2 on 2022-04-25 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_app', '0009_remove_commenton_fk_albumid_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_ticket_num', models.AutoField(primary_key=True, serialize=False)),
                ('made_on', models.DateTimeField(auto_now=True)),
                ('feedback_text', models.TextField()),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
