# Generated by Django 4.0.2 on 2022-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug')], default='Bug', max_length=50),
        ),
    ]
