# Generated by Django 4.0.4 on 2022-04-26 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_app', '0011_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('DESIGN', 'Design'), ('SUGGESTION', 'Suggestion'), ('MISC', 'Misc')], default='Bug', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasSpotify', models.BooleanField(default=False)),
                ('hasApple', models.BooleanField(default=False)),
                ('bandcampUserName', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
