# Generated by Django 4.0.4 on 2022-05-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0012_alter_feedback_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandcampusername',
            name='bc_username',
            field=models.CharField(default='Not Set', max_length=100),
        ),
    ]
