# Generated by Django 4.0.4 on 2022-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0013_alter_bandcampusername_bc_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotifyAcessToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
