# Generated by Django 4.0.4 on 2022-05-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0014_profile_spotifyacesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='spotifyAcessToken',
            new_name='spotifyAccessToken',
        ),
    ]
