# Generated by Django 4.0.4 on 2022-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0015_rename_spotifyacesstoken_profile_spotifyaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotifyRefreshToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
