# Generated by Django 4.0.4 on 2022-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_app', '0016_profile_spotifyrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spotifyAccessToken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotifyRefreshToken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
